name = "cf-worker-ws-dev-0415" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
UUID = "2673fa3c-88a8-4fde-910e-1b7e5af777bc"
